FROM python:3.12.11-alpine3.21

WORKDIR /SHACLViewer

COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip==25.0.* &&\
    python -m pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=run.py
ENV PYTHONUNBUFFERED=1
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5001

CMD flask run
